# T3 Foundation Gemstone Project [t3gemstone.org]
# SPDX-License-Identifier: Apache-2.0

version: '3'

vars:
  DEBOS_VERSION: '{{ .DEBOS_VERSION | default "v1.1.3-custom" }}'
  DISTRO_HOSTNAME: '{{ .DISTRO_BASE }}-{{ .DISTRO_SUITE }}'
  SYSROOT_PATH: '{{ .BUILD_DIR }}/sysroot'

tasks:

  docker-build:
    internal: true
    cmds:
      - task: :fetch
      - docker run --rm --privileged multiarch/qemu-user-static --reset -p yes >/dev/null # fix exec format error
      - cd src/debos && docker build --tag t3gemstone/debos:{{ .DEBOS_VERSION }} --file docker/Dockerfile .
    status:
      - docker image inspect t3gemstone/debos:{{ .DEBOS_VERSION }}

  docker-run:
    internal: true
    vars:
      DOCKER_OPTIONS: '{{ default "" .DOCKER_OPTIONS }}'
      PROGRAM_OPTIONS: '{{ default "" .PROGRAM_OPTIONS }}'
    cmds:
      - docker run --rm --privileged multiarch/qemu-user-static --reset -p yes >/dev/null # fix exec format error
      - task: docker-build
      - docker run
          --rm
          --privileged
          --interactive
          --tty
          --workdir /recipes
          --volume ./distro:/recipes
          --volume {{ .DEBOS_DIR }}:/debos
          --cap-add=SYS_ADMIN
          --security-opt apparmor=unconfined
          --security-opt label=disable
          --cgroupns=host
          {{ .DOCKER_OPTIONS }}
          t3gemstone/debos:{{ .DEBOS_VERSION }} {{ .PROGRAM_OPTIONS }}

  create:
    silent: true
    vars: { RECIPE_NAME: '{{ .RECIPE_NAME | default "rootfs.yml" }}' }
    cmds:
      - task: docker-run
        vars: {
          DOCKER_OPTIONS: '--entrypoint /usr/local/bin/debos',
          PROGRAM_OPTIONS:
           '--disable-fakemachine
            --rootdir=/debos
            --artifactdir=/debos
            --scratchdir=/debos
            --template-var="base:{{ .DISTRO_BASE }}"
            --template-var="suite:{{ .DISTRO_SUITE }}"
            --template-var="type:{{ .DISTRO_TYPE }}"
            --template-var="hostname:{{ .DISTRO_HOSTNAME }}"
            {{ .RECIPE_NAME }}'
        }
      - task: sysroot

  chroot:
    silent: true
    cmds:
      - task: docker-run
        vars: {
          DOCKER_OPTIONS: '--entrypoint /bin/bash',
          PROGRAM_OPTIONS: '-c "hostname {{ .DISTRO_HOSTNAME }} && mount proc /debos/root/proc -t proc && mount sysfs /debos/root/sys -t sysfs && chroot /debos/root /bin/bash --rcfile /root/.profile"'
        }

  sysroot:
    silent: true
    cmds:
      - task: :fetch
      - |
        DIRS_TO_COPY=(
            "/usr/include/"
            "/usr/lib/"
            "/usr/local/include/"
            "/usr/local/lib/"
            "/usr/share/pkgconfig/"
        )

        for dir in "${DIRS_TO_COPY[@]}"; do
            if [ -d "{{ .DEBOS_DIR }}/root$dir" ]; then
                echo "Copying $dir..."
                rsync --archive --sparse --delete --mkpath "{{ .DEBOS_DIR }}/root$dir" "{{ .SYSROOT_PATH }}$dir"
            else
                echo "Warning: Directory {{ .DEBOS_DIR }}/root$dir does not exist, skipping."
            fi
        done
      - '{{ .SYMLINK_FIXER_PATH }} {{ .SYSROOT_PATH }} >/dev/null'
      - ln -sf usr/lib "{{ .SYSROOT_PATH }}/lib"
